name: Prison
author: Primus
description: "Prison, huraaaaay :D"
version: 1.0.0
api: [1.12.0, 1.13.0, 2.0.0]
main: prison\Prison
depend: PurePerms
soft-depend: [EconomyAPI, MassiveEconomy, PocketMoney, GoldStd]

permissions:
 prison.*:
  default: false
  description: "Allows all Prison features"
  children:
   prison.rankup:
    description: "Allows player to rankup"
    default: true
