name: Prison
author: Primus
description: "Prison, huraaaaay :D"
version: 1.0.0
api: [1.12.0, 1.13.0, 2.0.0]
main: prison\Prison

permissions:
 prison.*:
  default: false
  child:
   prison.rankup:
    default: true